# Generated by Django 2.0 on 2020-11-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_workers', '0002_historicalmedicaldata_recentmedicaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmedicaldata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='recentmedicaldata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
