# Generated by Django 2.0 on 2020-11-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthcare_workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('patientID', models.IntegerField(unique=True)),
                ('admissionDate', models.DateField()),
                ('dischargeDate', models.DateField(null=True)),
                ('bed', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='healthcare_workers.Bed')),
            ],
        ),
    ]
