# Generated by Django 2.0 on 2020-11-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dischargeDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
