# Generated by Django 2.0 on 2020-11-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20201114_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='healthcare_workers.Bed'),
        ),
    ]
