# Generated by Django 2.0 on 2020-11-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20201114_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dischargeDate',
        ),
    ]
